[Action_Bar]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Boss_Bar]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Closed_Caption]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Crosshair]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Debug_Screen]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Hotbar_Group]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 100

[Player_List]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Scoreboard]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Screen_Title]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Status_Effect]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Toast_Message]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0

[Tooltip]
	Display = true
	# Default: 100
	# Range: 0 ~ 200
	Resizer = 100
	# Default: 0
	# Range: -100 ~ 100
	OffsetX = 0
	# Default: 0
	# Range: -100 ~ 100
	OffsetY = 0
