#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon May 25 19:29:31 MDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=5
shaderPack=ComplementaryUnbound_r5.8.1.zip
